import 'package:flutter/cupertino.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';

import 'Album/Album.dart';
import 'Album/AlbumList.dart';

class Coin extends StatelessWidget {
  Autogenerated snapshot;
  Coin(this.snapshot);

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 50,
      width: 400,
      child: Row(
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Image.network(
              snapshot.image.toString(),
              height: 35,
            ),
          ),
          Text(
            "   " + snapshot.symbol.toString(),
            style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
          Text(
            "   " + snapshot.currentPrice.toString(),
            style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold),
          ),
          Text(
            "   " + snapshot.priceChange24h.toString(),
            style: TextStyle(fontSize: 17, fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }
}
