import 'Album.dart';

class AlbumList {
  final List<Autogenerated> albums;
  const AlbumList({required this.albums});

  factory AlbumList.FromJson(List<dynamic> ParsedJson) {
    List<Autogenerated> albums;
    albums = ParsedJson.map((e) => Autogenerated.fromJson(e)).toList();
    return new AlbumList(albums: albums);
  }
}
